//! Byte source for the PDF reader — either an owned buffer (small inputs, tests,
//! generated bytes) or a memory-mapped file.
//!
//! Mapping keeps huge inputs OUT of the heap: the OS pages them in on demand and
//! can evict the (read-only) pages under memory pressure, so opening a 200 MB
//! PDF on a phone no longer risks the OOM killer at read time. Both variants
//! deref to `[u8]`, so the offset-based parser is identical either way.
use std::fs::File;
use std::ops::Deref;
use std::path::Path;

pub enum Bytes {
    Owned(Vec<u8>),
    Mapped(memmap2::Mmap),
}

impl Bytes {
    /// Memory-map a file read-only.
    pub fn map_file(path: &Path) -> std::io::Result<Bytes> {
        let file = File::open(path)?;
        // SAFETY: we only ever read the mapping. The one hazard is another
        // process truncating the file out from under us (→ SIGBUS); acceptable
        // for a short-lived, local compression of a user-chosen file.
        let mmap = unsafe { memmap2::Mmap::map(&file)? };
        Ok(Bytes::Mapped(mmap))
    }

    /// Open a path, preferring an mmap and falling back to a full read (e.g. on
    /// filesystems / zero-length files where mmap is unavailable or rejected).
    pub fn open(path: &Path) -> std::io::Result<Bytes> {
        match Self::map_file(path) {
            Ok(b) => Ok(b),
            Err(_) => Ok(Bytes::Owned(std::fs::read(path)?)),
        }
    }

    /// Materialise into an owned `Vec` (copies a mapping). Used when we must hand
    /// back ownership of bytes we validated.
    pub fn into_vec(self) -> Vec<u8> {
        match self {
            Bytes::Owned(v) => v,
            Bytes::Mapped(m) => m.to_vec(),
        }
    }
}

impl Deref for Bytes {
    type Target = [u8];
    fn deref(&self) -> &[u8] {
        match self {
            Bytes::Owned(v) => v,
            Bytes::Mapped(m) => m,
        }
    }
}

impl From<Vec<u8>> for Bytes {
    fn from(v: Vec<u8>) -> Self {
        Bytes::Owned(v)
    }
}
